2024-12-11 07:32:13,749 Pulling cleaned dataset from WandB
wandb: Downloading large artifact cleaned_credit_card_data:latest, 85.55MB. 1 files...
wandb:   1 of 1 files downloaded.
Done. 0:0:0.2
2024-12-11 07:32:15,988 Dataset loaded successfully with shape: (1296675, 15)
2024-12-11 07:32:15,989 Creating new column 'trans_type'.
2024-12-11 07:32:16,003 New column 'trans_type' added.
2024-12-11 07:32:16,003 Loading pre-mapped lat and long coordinates for customer's city and state, and using it to create 'cust_lat' and 'cust_long' columns.
Traceback (most recent call last):
  File "C:\Users\eelil\OneDrive\Desktop\Capstone\Machine_Learning_Analysis_of_Bank_Fraud\data\data_preparation\feature_creation.py", line 236, in <module>
    feature_creation()
  File "C:\Users\eelil\OneDrive\Desktop\Capstone\Machine_Learning_Analysis_of_Bank_Fraud\data\data_preparation\feature_creation.py", line 79, in feature_creation
    cust_loc = pd.read_parquet(r"artifacts/cust_loc_data-v0/cust_loc.parquet")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\pandas\io\parquet.py", line 667, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\pandas\io\parquet.py", line 267, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\pandas\io\parquet.py", line 140, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\pandas\io\common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/cust_loc_data-v0/cust_loc.parquet'
